databases:
  - name: gigdaemon-db
    region: frankfurt
    plan: free

services:
  - type: web
    name: gigdaemon
    region: frankfurt
    plan: free
    runtime: docker
    healthCheckPath: /up
    envVars:
      # --- ЯВНОЕ, ТУПОЕ, НАДЕЖНОЕ ПОДКЛЮЧЕНИЕ К БАЗЕ ДАННЫХ ---
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: gigdaemon-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: gigdaemon-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: gigdaemon-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: gigdaemon-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gigdaemon-db
          property: password

      # --- Настройки Приложения ---
      - key: APP_URL
        value: https://gigdaemon.onrender.com # Замени на свой
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr

      # --- Настройки для работы в продакшене ---
      - key: CACHE_DRIVER
        value: array
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: cookie
      - key: SESSION_LIFETIME
        value: 120
      
      # --- Секрет ---
      - key: APP_KEY
        sync: false