databases:
  - name: gigdaemon-db
    region: frankfurt
    plan: free

services:
  - type: web
    name: gigdaemon
    region: frankfurt
    plan: free
    runtime: docker
    healthCheckPath: /up
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gigdaemon-db
          property: connectionString
      - key: APP_URL
        # Это значение Render подставит автоматически после первого успешного деплоя.
        # Временное значение нужно, чтобы Blueprint прошел валидацию.
        value: https://gigdaemon.onrender.com
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      # Секрет, который ты должен был уже добавить вручную в интерфейсе Render
      - key: APP_KEY
        sync: false
    # Указываем, что миграции нужно запускать при каждом деплое
    preDeployCommand: "php artisan migrate --force"