# databases: A list of PostgreSQL databases.
databases:
  - name: gigdaemon-db
    region: frankfurt
    plan: free # free plan is available for databases
    postgresMajorVersion: 16

# services: A list of non-PostgreSQL services.
services:
  # type: web for a web service
  - type: web
    name: gigdaemon
    region: frankfurt
    # runtime: docker for services that build an image from a Dockerfile.
    runtime: docker
    plan: free # free plan is available for web services
    # healthCheckPath: The path of the service's health check endpoint.
    healthCheckPath: /up
    envVars:
      # To reference a value from PostgreSQL, use fromDatabase
      - key: DATABASE_URL
        fromDatabase:
          name: gigdaemon-db
          property: connectionString
      - key: APP_URL
        # We will set this manually after the first deploy
        # because fromService property 'url' is invalid.
        value: https://placeholder.com
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      # For secrets, use sync: false. Render will prompt for it.
      - key: APP_KEY
        sync: false