# Это Blueprint. Единый, правильный, выстраданный чертеж.
# Основан на документации, которую нашел ты.

# === КЛЮЧЕВОЕ ИЗМЕНЕНИЕ: Базы данных объявляются в отдельном списке ===
databases:
  - name: gigdaemon-db
    # Здесь не нужен 'type', потому что сам список 'databases' определяет тип.
    region: frankfurt
    plan: free
    postgresMajorVersion: 15

# === А сервисы - в своем собственном списке ===
services:
  # Наш веб-сервер на Laravel
  - type: web # Это правильный тип для веб-сервиса
    name: gigdaemon
    region: frankfurt
    plan: free
    runtime: php
    buildCommand: |
      composer install --no-dev --no-interaction --optimize-autoloader
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      npm install
      npm run build
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: gigdaemon
          property: url
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DATABASE_URL
        fromService:
          # Здесь 'psql' - это правильный тип ресурса, на который мы ссылаемся.
          type: psql
          name: gigdaemon-db
          property: connectionString
      - key: APP_KEY
        sync: false # Секрет, который мы добавим вручную в интерфейсе Render.