databases:
  - name: gigdaemon-db
    region: frankfurt
    plan: free

services:
  # --- НАШ НОВЫЙ СЕРВИС REDIS ---
  - type: redis
    name: gigdaemon-redis
    region: frankfurt
    plan: free
    maxmemoryPolicy: allkeys-lru # Стратегия вытеснения, когда память кончится

  - type: web
    name: gigdaemon
    region: frankfurt
    plan: free
    runtime: docker
    healthCheckPath: /up
    envVars:
      # --- Старые переменные ---
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: gigdaemon-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: gigdaemon-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: gigdaemon-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: gigdaemon-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gigdaemon-db
          property: password
      - key: APP_URL
        value: https://gigdaemon.onrender.com # Убедись, что это твой URL
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      
      # --- Новые и измененные переменные ---
      - key: REDIS_HOST
        fromService:
          type: redis
          name: gigdaemon-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: gigdaemon-redis
          property: port
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: gigdaemon-redis
          property: password
      - key: CACHE_DRIVER
        value: redis # Было 'array'
      - key: QUEUE_CONNECTION
        value: redis # Было 'sync'
      - key: SESSION_DRIVER
        value: redis # Было 'cookie'
      - key: SESSION_LIFETIME
        value: 120
      
      # --- Секрет ---
      - key: APP_KEY
        sync: false