# databases: A list of PostgreSQL databases.
databases:
  - name: gigdaemon-db
    region: frankfurt
    plan: free

# services: A list of non-PostgreSQL services.
services:
  # type: web for a web service
  - type: web
    name: gigdaemon
    region: frankfurt
    plan: free
    # runtime: docker for services that build an image from a Dockerfile.
    runtime: docker
    healthCheckPath: /up
    # === ГЛАВНОЕ ИЗМЕНЕНИЕ: ГРЯЗНЫЙ ХАК ===
    # Мы объединяем миграцию и запуск сервера в одну команду.
    # Это будет работать на бесплатном тарифе.
    startCommand: "php artisan migrate --force && php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      # To reference a value from PostgreSQL, use fromDatabase
      - key: DATABASE_URL
        fromDatabase:
          name: gigdaemon-db
          property: connectionString
      - key: APP_URL
        # We will set this manually after the first deploy
        value: https://placeholder.com
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      # For secrets, use sync: false. Render will prompt for it.
      - key: APP_KEY
        sync: false